apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ue4-pixelsteraming-gaming-eks
  region: ap-south-1

nodeGroups:
  - name: ng-cpu-group01
    instanceType: m5.large
    #desiredCapacity: 1
    #minSize: 1
    #maxSize: 2
    labels: 
      app.pixel/turn: "true"
      app.pixel/envoy: "true"
    ssh:
      allow: true
      publicKeyName: test-user
  - name: ng-gpu-group01
    instanceType: g4dn.xlarge
    #desiredCapacity: 1
    #minSize: 1
    #maxSize: 2
    labels: 
       app.pixel/streamer: "true"
    taints:
       app.pixel/streamer: "true:NoSchedule"
    ssh:
      allow: true
      publicKeyName: test-user
