apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-stream
  namespace: ue4
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30