apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/component: unreal
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stream-autoscaler
    app.kubernetes.io/part-of: pixelstreaming-stack
    app.kubernetes.io/version: 0.0.1
    version: 0.0.1
  name: stream-autoscaler
  namespace: ue4
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 2
      - periodSeconds: 15
        type: Percent
        value: 10
      stabilizationWindowSeconds: 0
  maxReplicas: 10
  metrics:
  - object:
      describedObject:
    type: Object
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stream