apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-app-rb
  namespace: ue4
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: ue4
roleRef:
  kind: Role
  name: scale-app-role
  apiGroup: rbac.authorization.k8s.io
